'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Charge
    Public Property Charge_ID As Integer
    Public Property Charge1 As Nullable(Of Decimal)
    Public Property Charge_Name As String

    Public Overridable Property LPOes As ICollection(Of LPO) = New HashSet(Of LPO)
    Public Overridable Property Quotations As ICollection(Of Quotation) = New HashSet(Of Quotation)
    Public Overridable Property Quotations1 As ICollection(Of Quotation) = New HashSet(Of Quotation)

End Class
