'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ClearingAgentContract
    Public Property ClearingAgentContractID As Integer
    Public Property ClearingAgentContractDate As Nullable(Of Date)
    Public Property ClearingAgentContractRefNo As String
    Public Property ClearingAgentDetailsID As Nullable(Of Integer)
    Public Property ClearingAgentContractClass As String
    Public Property ClearingAgentContractBales As Nullable(Of Decimal)
    Public Property ClearingAgentContractQtyApproved As Nullable(Of Decimal)
    Public Property Version As Byte()
    Public Property ClearingAgentContractBOL As String

End Class
