'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ClearingAgent
    Public Property ClearingAgentID As Integer
    Public Property ClearingAgentName As String
    Public Property ClearingAgentCepsDuty As Nullable(Of Decimal)
    Public Property ClearingAgentMolShipping As Nullable(Of Decimal)
    Public Property ClearingAgentMpsCharges As Nullable(Of Decimal)
    Public Property ClearingAgentGphaCharges As Nullable(Of Decimal)
    Public Property ClearingAgentForkLift As Nullable(Of Decimal)
    Public Property ClearingAgentTransportation As Nullable(Of Decimal)
    Public Property ClearingAgentInterestCharges As Nullable(Of Decimal)
    Public Property ClearingAgentLabour As Nullable(Of Decimal)
    Public Property ClearingAgentAgencyFee As Nullable(Of Decimal)
    Public Property Version As Byte()
    Public Property ClearingAgentAgencyDate As Nullable(Of Date)
    Public Property ClearingAgentAgencyRefNo As String
    Public Property ClearingAgentDetailsID As Nullable(Of Integer)
    Public Property ClearingAgentInvoice As String
    Public Property ClearingAgentVAT As Nullable(Of Decimal)
    Public Property ClearingAgentEPA As Nullable(Of Decimal)
    Public Property ClearingAgentDescription As String
    Public Property ClearingAgentShippingLine As String
    Public Property ClearingAgentContainerAgent As String
    Public Property ClearingAgentDumurrage As Nullable(Of Decimal)
    Public Property IFTNo As String
    Public Property BOLNo As String
    Public Property SubTotal As Nullable(Of Decimal)
    Public Property ClearingAgentContractID As Nullable(Of Integer)
    Public Property ClearingAgentQuantityCleared As Nullable(Of Decimal)

End Class
