'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ClearingAgentDetail
    Public Property ClearingAgentDetailsID As Integer
    Public Property ClearingAgentDetailsName As String
    Public Property ClearingAgentDetailsPhone As String
    Public Property ClearingAgentDetailsAddress As String
    Public Property Version As Byte()

End Class
