'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Department
    Public Property Department_ID As Integer
    Public Property Department1 As String
    Public Property Version As Byte()

    Public Overridable Property Tenders As ICollection(Of Tender) = New HashSet(Of Tender)

End Class
