'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LPO_Status
    Public Property LPO_Status_ID As Integer
    Public Property LPO_Status1 As String
    Public Property Version As Byte()

    Public Overridable Property LPOes As ICollection(Of LPO) = New HashSet(Of LPO)

End Class
