'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LPO_Products
    Public Property LPO_Product_ID As Integer
    Public Property LPO_Product As String
    Public Property LPO_Product_Description As String
    Public Property LPO_Product_Quantity As Nullable(Of Decimal)
    Public Property Unit_Of_Measure_ID As Nullable(Of Integer)
    Public Property LPO_Product_UnitPrice As Nullable(Of Decimal)
    Public Property LPO_Product_Total As Nullable(Of Decimal)

End Class
