'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PreContract
    Public Property PContractID As Integer
    Public Property PContractName As String
    Public Property PContractIFT As String
    Public Property PContractProcMethod As String
    Public Property PContractPrepDate As Nullable(Of Date)
    Public Property PContractTenderInvitationDate As Nullable(Of Date)
    Public Property PContractTenderClosingDate As Nullable(Of Date)
    Public Property PContractSubEvalReport As Nullable(Of Date)
    Public Property PContractAppFinAuth As Nullable(Of Date)
    Public Property PContractAmount As Nullable(Of Decimal)
    Public Property PContractAward As Nullable(Of Date)
    Public Property PContractSign As Nullable(Of Date)
    Public Property PContractArrival As Nullable(Of Date)
    Public Property PContractInspection As Nullable(Of Date)
    Public Property Remarks As String
    Public Property Version As Byte()
    Public Property CurrencyID As Nullable(Of Integer)

End Class
