'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Quotation
    Public Property Quotation_ID As Integer
    Public Property Supplier_ID As Nullable(Of Integer)
    Public Property Tender_ID As Nullable(Of Integer)
    Public Property Staff_ID As Nullable(Of Integer)
    Public Property Quotation_Date As Nullable(Of Date)
    Public Property Quotation_VAT As Nullable(Of Integer)
    Public Property Quotation_NHIL As Nullable(Of Integer)
    Public Property Quotation_Remarks As String
    Public Property Quotation_Total As Nullable(Of Decimal)
    Public Property Version As Byte()
    Public Property LPO As String
    Public Property Quotation_Tax As Nullable(Of Decimal)
    Public Property Quotation_Tax_Comments As String

    Public Overridable Property Charge As Charge
    Public Overridable Property Charge1 As Charge
    Public Overridable Property LPOes As ICollection(Of LPO) = New HashSet(Of LPO)
    Public Overridable Property Quotation_Products As ICollection(Of Quotation_Products) = New HashSet(Of Quotation_Products)
    Public Overridable Property Supplier As Supplier
    Public Overridable Property Tender As Tender

End Class
