'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Supplier_Categories
    Public Property Supplier_Category_ID As Integer
    Public Property Supplier_Category As String

    Public Overridable Property Suppliers As ICollection(Of Supplier) = New HashSet(Of Supplier)

End Class
