'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Supplier
    Public Property Supplier_ID As Integer
    Public Property Supplier_Name As String
    Public Property Supplier_Address As String
    Public Property Supplier_City As String
    Public Property Supplier_Region As String
    Public Property Supplier_Country As String
    Public Property Supplier_Location As String
    Public Property Supplier_Registration_Date As Nullable(Of Date)
    Public Property Supplier_Fax As String
    Public Property Supplier_Telephone As String
    Public Property Supplier_Email As String
    Public Property Supplier_Contact_Person As String
    Public Property Supplier_Website As String
    Public Property Staff_ID As Nullable(Of Integer)
    Public Property Supplier_Category_ID As Nullable(Of Integer)
    Public Property Version As Byte()
    Public Property Supplier_SSNIT As String
    Public Property Supplier_IRS As String

    Public Overridable Property Quotations As ICollection(Of Quotation) = New HashSet(Of Quotation)
    Public Overridable Property Supplier_Categories As Supplier_Categories

End Class
