'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tax
    Public Property Tax_ID As Integer
    Public Property Tax_Name As String
    Public Property Tax_Amount As Nullable(Of Decimal)

End Class
