'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tema
    Public Property TemaID As Integer
    Public Property TemaItemDescription As String
    Public Property TemaBODNumberHouseCopy As String
    Public Property TemaNameofShippingLine As String
    Public Property TemaMasterBOD As String
    Public Property TemaArrivalDate As Nullable(Of Date)
    Public Property TemaQuantity As Nullable(Of Decimal)
    Public Property Version As Byte()
    Public Property UnitOfMeasureID As Nullable(Of Integer)

End Class
