'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tender_Products
    Public Property Tender_Product_ID As Integer
    Public Property Tender_ID As Nullable(Of Integer)
    Public Property Tender_Product As String
    Public Property Tender_Product_Description As String
    Public Property Tender_Product_Quantity As Nullable(Of Decimal)
    Public Property Unit_Of_Measure_ID As Nullable(Of Integer)
    Public Property Tender_UnitPrice As Nullable(Of Decimal)
    Public Property Version As Byte()

    Public Overridable Property Tender As Tender

End Class
