'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tender
    Public Property Tender_ID As Integer
    Public Property Tender_No As String
    Public Property Tender_Title As String
    Public Property Tender_Start_Date As Nullable(Of Date)
    Public Property Tender_Closing_Date As Nullable(Of Date)
    Public Property Tender_Description As String
    Public Property Currency_ID As Nullable(Of Integer)
    Public Property Tender_Remarks As String
    Public Property Department_ID As Nullable(Of Integer)
    Public Property Tender_Expected_Delivery_Date As Nullable(Of Date)
    Public Property Staff_ID As Nullable(Of Integer)
    Public Property Tender_Entry_Date As Nullable(Of Date)
    Public Property Tender_Approved_By As String
    Public Property Tender_Approval_Date As Nullable(Of Date)
    Public Property Version As Byte()
    Public Property Tender_Status As String
    Public Property Tender_Status_ID As Nullable(Of Integer)
    Public Property Tender_Memo_No As String
    Public Property Tender_User As String

    Public Overridable Property Currency As Currency
    Public Overridable Property Department As Department
    Public Overridable Property Quotations As ICollection(Of Quotation) = New HashSet(Of Quotation)
    Public Overridable Property Staff As Staff
    Public Overridable Property Tender_Products As ICollection(Of Tender_Products) = New HashSet(Of Tender_Products)

End Class
