'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VPNContract
    Public Property ContractID As Integer
    Public Property Contract_IFTNo As String
    Public Property ContractNotification As Nullable(Of Date)
    Public Property ContractPerformanceBond As Nullable(Of Date)
    Public Property ContractDateSigned As Nullable(Of Date)
    Public Property ContractCreditDateEstablished As Nullable(Of Date)
    Public Property ContractAdvancePaymentGuarantee As Nullable(Of Date)
    Public Property ContractExpectedDeliveryDate As Nullable(Of Date)
    Public Property ContractActualDeliveryDate As Nullable(Of Date)
    Public Property ContractStatus As Nullable(Of Integer)
    Public Property Version As Byte()
    Public Property Contract_Let_Credit As String
    Public Property Contract_Credit As String
    Public Property ContractCompany As String
    Public Property ContractItem As String
    Public Property ContractQuantity As Nullable(Of Decimal)
    Public Property ContractValue As Nullable(Of Decimal)
    Public Property ContractRemarks As String
    Public Property ContractNotificationRemarks As String
    Public Property ContractPerformanceBondRemarks As String
    Public Property ContractDateSignedRemarks As String
    Public Property ContractCreditDateEstablishedRemarks As String
    Public Property ContractExpectedDeliveryDateRemarks As String
    Public Property ContractActualDeliveryDateRemarks As String
    Public Property Contract_CreditRemarks As String
    Public Property ContractDeliverySite As String
    Public Property ContractDeliverySiteRemarks As String
    Public Property ContractAdvancePaymentGuaranteeTalk As String
    Public Property CurrencyID As Nullable(Of Integer)
    Public Property UnitOfMeasureID As Nullable(Of Integer)

End Class
