'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Waybill
    Public Property WaybillID As Integer
    Public Property WaybillDate As Nullable(Of Date)
    Public Property WaybillReceipient As String
    Public Property WaybillNo As String
    Public Property ZoneID As Nullable(Of Integer)
    Public Property DestinationID As Nullable(Of Integer)
    Public Property WaybillVehicleNo As String
    Public Property WaybillServiceProviderID As Nullable(Of Integer)
    Public Property WaybillRefNo As String
    Public Property WaybillQty As Nullable(Of Decimal)
    Public Property TransactionTypeID As Nullable(Of Integer)
    Public Property ItemID As Nullable(Of Integer)
    Public Property WaybillBOL As String
    Public Property Version As Byte()
    Public Property IFTNo As String
    Public Property UnitOfMeasureID As Nullable(Of Integer)

End Class
